### ISSUE TITLE
Can't bind Hat Switch 1

### ISSUE THREAD

**Issue by thelazrus** [Aussiedroid/AD-EDWarthogEnhancedScript#13]
Hat Switch 1 has some auto chat stuff setup to auto type pre-defined statements that you can change in the user prefs. However, I would like to instead bind the four positions of that hat switch to something else as I do not have a need for the auto chat feature. Unfortunately, after playing around with a few of the config files, I can't seem to get it to bind to anything. Got close when it bound to 0,8,9 and right control or something like that. Hat wouldn't work, but when I pressed those keys on the keyboard they worked, strange.

**Comment by ClickerNZ** [comment]
1) If you want to bind H1 to do something else completely, then you need to edit AD_ED_v4.3.0.tmc file.
Specifically lines; 213, 214, 220, 221, 227, 228, 234 and 235
You need to replace the EXEC(...), commands with what you wish the switches to do.

2) If you give me an example of what you want to bind to instead, I can explain what you need to replace the "EXEC" statements with along with anything else you may need to change.

Clicker

**Comment by thelazrus** [comment]
Hello,
I specifically wanted to map that hat for thrusters. Up, down, left, right instead of the auto chat options. I ended up getting it to work i believe, but I've probably broken the other mappings that relate to the modify + hat usage, like the wingman commands.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by ClickerNZ** [comment]
If you don't want the chat functions, easiest way to swap out the H1 functionality is as follows:-

In AD_ED_v4.3.0.tmc...

At line 214, replace  EXEC("initSendChatString(chat_Basic_UP);"),
with; ThrustUp,

Similarly...
replace line 221 with; ThrustDown,
replace line 228 with; ThrustLeft,
replace line 235 with; ThrustRight,

You should not need to change anything else.

To use in game flick the Throttle Pinky switch Forward (ie "PSF") then H1U, D, L or R.
When finished with lateral thrusters, return Throttle Pinky Switch to the middle position (ie "PSM")

Hope this helps
Clicker

**Comment by Aussiedroid** [comment]
Hi thelazrus,

The hat switch in question, as ClickerNZ has explained, is programmed directly by the script. Mapping this in ED to something else will break the functionality. You will need to re-code the script if you wish to use that hat switch for something else. 

This is not a bug in the script, so I will resolve this issue today. 

Thanks for checking out the script,
AD
