### ISSUE TITLE
not sure how to use warthog to dis-engage Frame Shift Drive & Super Cruise

### ISSUE THREAD

**Issue by Yeeler** [Aussiedroid/AD-EDWarthogEnhancedScript#18]
press joy 4 didn't work

**Comment by Aussiedroid** [comment]
Hey Yeeler,

Thanks for checking out the script!

The FSD and SC is tied to the modifier you are pressing (Joy 4 - Pinky Trigger), but you __ALSO__ need to be holding that while you move the throttle to 100%. If Joy 4 is held and you go from 99-100% on the throttle axis it will trigger the FSD. Do the same action to disable if you want to stop the charging. For this just move the throttle down to 99% or less and move it quickly back to 100% when holding the Joy 4. You can also disengage or engage the FSD at the 0% mark on the throttle. So for example you could use 100% trigger to enable, but if you change your mind and want to disable, move the throttle down to 0% while holding Joy 4. You can choose what works best for you.

You will find this one is one of the more tricky ones to figure out, but there are a lot of mappings that use the modifiers like Joy 4 in combination with another toggle/button to map to other commands. Hopefully it will click once you have done a few and become second nature soon :)

Any questions let me know,
AD

**Comment by Yeeler** [comment]
Thank you very much. :-)
