### ISSUE TITLE
Odyssey changes - Planned Update ?

### ISSUE THREAD

**Issue by 3kynox** [Aussiedroid/AD-EDWarthogEnhancedScript#21]
Hello,

I just want to know if you planned to update this profile to use with Odyssey or maybe it is already usable.

Thanks anyway!

**Comment by macvern** [comment]
mostly working right now but sometimes going from on foot back to my ship the script aborts.  Also, seems that Odyssey keeps forgetting the binds so I have to re-link the vertical and lateral thrusters in the preferences.. (I'm using a thumbstick mod where the nubbin used to be on the Throttle).

**Comment by Aussiedroid** [comment]
Hey @3kynox,

Looks like you have hit me up on all channels haha! :) 

As responded elsewhere, its a WIP .. hoping to have some updates soon (tm). Should be working for the most for both 4.3 and 5.0 but will need some mappings done for the on-foot stuff.

Any issues, appreciate your feedback.

Cheers, AD
