### ISSUE TITLE
Docs-Maps

### ISSUE THREAD

**Issue by TrevL-gig** [Aussiedroid/AD-EDWarthogEnhancedScript#23]
Hi would you be up for sharing the original documents so that I can split them by headings as it will be easier to read in VR
![Advanced-Map](https://user-images.githubusercontent.com/72253661/170049690-4c439347-1fe7-4413-a0ba-889b16800ee0.jpg)
.

**Comment by Aussiedroid** [comment]
Hi @TrevL-gig,

Sorry for the late reply. Not around here as much anymore.

I don't mind sharing the PSD file if you want to try to decipher it for your own needs. I warn you though, it is a mess! :) 

You can find it here:

https://github.com/Aussiedroid/AD-EDWarthogEnhancedScript/tree/odyssey

_See file:_ HOTAS-Warthog-ED-Mappings2021-03.psd

What I generally would do for the updates is to do the updates in the main PSD file then copy over the image you shared above, but I will leave it to you. 

All the best!
AD
